UPDATE messages SET content_english = 'Your DigiD app <naam van apparaat> has just been activated with a once-only ID check. \\nPlease contact the DigiD helpdesk if you did not do this yourself. Opening hours 8:00 - 22:00 on working days (Dutch time). Telephonenumber: 088 123 65 55.' WHERE (id = '1');
UPDATE messages SET content_dutch = 'Uw DigiD app <naam van apparaat> is zojuist geactiveerd met een eenmalige ID-check. \\nNeem contact op met de DigiD helpdesk als u dit niet zelf heeft gedaan. Bereikbaar op werkdagen van 8:00 - 22:00 uur (Nederlandse tijd). Telefoonnummer: 088 123 65 55.' WHERE (id = '1');

UPDATE messages SET content_english = 'Your DigiD app <naam van apparaat> has just been activated. \\nPlease contact the DigiD helpdesk if you did not do this yourself. Opening hours 8:00 - 22:00 on working days (Dutch time). Telephonenumber: 088 123 65 55.' WHERE (id = '2');
UPDATE messages SET content_dutch = 'Uw DigiD app <naam van apparaat> is zojuist geactiveerd. \\nNeem contact op met de DigiD helpdesk als u dit niet zelf heeft gedaan. Bereikbaar op werkdagen van 8:00 - 22:00 uur (Nederlandse tijd). Telefoonnummer: 088 123 65 55' WHERE (id = '2');

UPDATE messages SET content_english = 'Your SMS verification has just been activated. \\nPlease contact the DigiD helpdesk if you did not do this yourself. Opening hours 8:00 - 22:00 on working days (Dutch time). Telephonenumber: 088 123 65 55.' WHERE (id = '3');
UPDATE messages SET content_dutch = 'Uw sms-controle is zojuist geactiveerd. \\nNeem contact op met de DigiD helpdesk als u dit niet zelf heeft gedaan. Bereikbaar op werkdagen van 8:00 - 22:00 uur (Nederlandse tijd). Telefoonnummer: 088 123 65 55.' WHERE (id = '3');

UPDATE messages SET content_english = 'Your email address has just been added in My DigiD. \\nPlease contact the DigiD helpdesk if you did not do this yourself. Opening hours 8:00 - 22:00 on working days (Dutch time). Telephonenumber: 088 123 65 55.' WHERE (id = '4');
UPDATE messages SET content_dutch = 'Uw e-mailadres is zojuist toegevoegd in Mijn DigiD. \\nNeem contact op met de DigiD helpdesk als u dit niet zelf heeft gedaan. Bereikbaar op werkdagen van 8:00 - 22:00 uur (Nederlandse tijd). Telefoonnummer: 088 123 65 55.' WHERE (id = '4');

UPDATE messages SET content_english = 'Your email address has just been changed in My DigiD. \\nPlease contact the DigiD helpdesk if you did not do this yourself. Opening hours 8:00 - 22:00 on working days (Dutch time). Telephonenumber: 088 123 65 55.' WHERE (id = '5');
UPDATE messages SET content_dutch = 'Uw e-mailadres is zojuist gewijzigd in Mijn DigiD. \\nNeem contact op met de DigiD helpdesk als u dit niet zelf heeft gedaan. Bereikbaar op werkdagen van 8:00 - 22:00 uur (Nederlandse tijd). Telefoonnummer: 088 123 65 55.' WHERE (id = '5');
