/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DropdownItem } from "./components/interfaces/DropdownItem";
export namespace Components {
    interface LogiusButton {
        "theme": string;
        "withArrow": boolean;
    }
    interface LogiusCol {
        "flex": boolean;
        "lg": number;
        "md": number;
        "sm": number;
        "xl": number;
        "xs": number;
    }
    interface LogiusDropdown {
        "_id": string;
        "header": string;
        "hint": string;
        "options": Array<DropdownItem>;
        "selected": string;
    }
    interface LogiusInputField {
        "_id": string;
        "currentValue": string;
        "header": string;
        "hint": string;
    }
    interface LogiusPanel {
    }
    interface LogiusRow {
    }
    interface LogiusSpinner {
    }
    interface LogiusTable {
        "mapping": Object;
        "rows": Array<object>;
        "tableTitle": string;
    }
}
declare global {
    interface HTMLLogiusButtonElement extends Components.LogiusButton, HTMLStencilElement {
    }
    var HTMLLogiusButtonElement: {
        prototype: HTMLLogiusButtonElement;
        new (): HTMLLogiusButtonElement;
    };
    interface HTMLLogiusColElement extends Components.LogiusCol, HTMLStencilElement {
    }
    var HTMLLogiusColElement: {
        prototype: HTMLLogiusColElement;
        new (): HTMLLogiusColElement;
    };
    interface HTMLLogiusDropdownElement extends Components.LogiusDropdown, HTMLStencilElement {
    }
    var HTMLLogiusDropdownElement: {
        prototype: HTMLLogiusDropdownElement;
        new (): HTMLLogiusDropdownElement;
    };
    interface HTMLLogiusInputFieldElement extends Components.LogiusInputField, HTMLStencilElement {
    }
    var HTMLLogiusInputFieldElement: {
        prototype: HTMLLogiusInputFieldElement;
        new (): HTMLLogiusInputFieldElement;
    };
    interface HTMLLogiusPanelElement extends Components.LogiusPanel, HTMLStencilElement {
    }
    var HTMLLogiusPanelElement: {
        prototype: HTMLLogiusPanelElement;
        new (): HTMLLogiusPanelElement;
    };
    interface HTMLLogiusRowElement extends Components.LogiusRow, HTMLStencilElement {
    }
    var HTMLLogiusRowElement: {
        prototype: HTMLLogiusRowElement;
        new (): HTMLLogiusRowElement;
    };
    interface HTMLLogiusSpinnerElement extends Components.LogiusSpinner, HTMLStencilElement {
    }
    var HTMLLogiusSpinnerElement: {
        prototype: HTMLLogiusSpinnerElement;
        new (): HTMLLogiusSpinnerElement;
    };
    interface HTMLLogiusTableElement extends Components.LogiusTable, HTMLStencilElement {
    }
    var HTMLLogiusTableElement: {
        prototype: HTMLLogiusTableElement;
        new (): HTMLLogiusTableElement;
    };
    interface HTMLElementTagNameMap {
        "logius-button": HTMLLogiusButtonElement;
        "logius-col": HTMLLogiusColElement;
        "logius-dropdown": HTMLLogiusDropdownElement;
        "logius-input-field": HTMLLogiusInputFieldElement;
        "logius-panel": HTMLLogiusPanelElement;
        "logius-row": HTMLLogiusRowElement;
        "logius-spinner": HTMLLogiusSpinnerElement;
        "logius-table": HTMLLogiusTableElement;
    }
}
declare namespace LocalJSX {
    interface LogiusButton {
        "theme"?: string;
        "withArrow"?: boolean;
    }
    interface LogiusCol {
        "flex"?: boolean;
        "lg"?: number;
        "md"?: number;
        "sm"?: number;
        "xl"?: number;
        "xs"?: number;
    }
    interface LogiusDropdown {
        "_id"?: string;
        "header"?: string;
        "hint"?: string;
        "onChangeCallback"?: (event: CustomEvent<any>) => void;
        "options"?: Array<DropdownItem>;
        "selected"?: string;
    }
    interface LogiusInputField {
        "_id"?: string;
        "currentValue"?: string;
        "header"?: string;
        "hint"?: string;
        "onChangeCallback"?: (event: CustomEvent<any>) => void;
    }
    interface LogiusPanel {
    }
    interface LogiusRow {
    }
    interface LogiusSpinner {
    }
    interface LogiusTable {
        "mapping"?: Object;
        "rows"?: Array<object>;
        "tableTitle"?: string;
    }
    interface IntrinsicElements {
        "logius-button": LogiusButton;
        "logius-col": LogiusCol;
        "logius-dropdown": LogiusDropdown;
        "logius-input-field": LogiusInputField;
        "logius-panel": LogiusPanel;
        "logius-row": LogiusRow;
        "logius-spinner": LogiusSpinner;
        "logius-table": LogiusTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "logius-button": LocalJSX.LogiusButton & JSXBase.HTMLAttributes<HTMLLogiusButtonElement>;
            "logius-col": LocalJSX.LogiusCol & JSXBase.HTMLAttributes<HTMLLogiusColElement>;
            "logius-dropdown": LocalJSX.LogiusDropdown & JSXBase.HTMLAttributes<HTMLLogiusDropdownElement>;
            "logius-input-field": LocalJSX.LogiusInputField & JSXBase.HTMLAttributes<HTMLLogiusInputFieldElement>;
            "logius-panel": LocalJSX.LogiusPanel & JSXBase.HTMLAttributes<HTMLLogiusPanelElement>;
            "logius-row": LocalJSX.LogiusRow & JSXBase.HTMLAttributes<HTMLLogiusRowElement>;
            "logius-spinner": LocalJSX.LogiusSpinner & JSXBase.HTMLAttributes<HTMLLogiusSpinnerElement>;
            "logius-table": LocalJSX.LogiusTable & JSXBase.HTMLAttributes<HTMLLogiusTableElement>;
        }
    }
}
